name: mruby
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- README.md
- gen_mgemdata.rb
